spring:
  ai:
#   api-key: ""
#   chat:
#     options:
#       model: gpt-3.5-turbo
#   embedding:
#     options:
#       models: text-embedding-ada-002
  jpa:
    generate-ddl: true

management:
  wavefront:
    api-token: cfd06c63-7ef3-4f3d-a48f-8bf662bf2453// this is a fake token since wavefront lib expects a token, though this is not used for authentication to collector for ingestion
    uri: http://telegraf.hub-collector.service.internal:8765
    application:
      name: spring-metal
      service-name: spring-metal-ui
      custom-tags:
        instance_guid: ${CF_INSTANCE_GUID}
  metrics:
    tags:
      instance_guid: ${CF_INSTANCE_GUID}
  tracing:
    sampling:
      probability: 0.5
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      show-values: ALWAYS
      git:
        mode: full
      spring:
        boot:
          version: '@app.spring.boot.version@'
      app:
        version: @project.version@
    health:
      enabled: true
      show-details: always
    env:
      show-values: ALWAYS
  
---
logging:
  level:
    root: INFO
---
spring:
  config:
    activate:
      on-profile: http2

server:
  http2:
    enabled: true
  port: 8443
  #ssl:
  #  enabled: true
  #  key-alias: demo
  #  key-store: classpath:keystore.bks
  #  key-store-password: changeit
  #  key-password: changeit
  #  key-store-type: "BCFKS"
    
---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: "jdbc:mysql://localhost/music"
    driver-class-name: com.mysql.jdbc.Driver
    username:
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect

---
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: "jdbc:postgresql://localhost/music"
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
---
#tanzu:
#  governance:
#    fips:
#      exit-on-failure: true
