#cloud-config
users:
  - default
  - name: vmware
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    # Password set to Admin!23
    passwd: '$1$salt$RUXm1Lco5jcJ7OBw.hRQi1'
    shell: /bin/bash
ssh_pwauth: true

write_files:
  - content: |
      VMSVC Says Hello World
    path: /home/vmware/helloworld

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

package_update: true

packages:
  - docker-ce
  - docker-ce-cli

runcmd:
  - sudo docker run --name nginx -p 80:80 -d harbor.tanzuworld.com/openso/nginx
