apiVersion: v1
kind: Service
metadata:
  name: cbdemo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: cbdemo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cbdemo
  template:
    metadata:
      labels:
        app: cbdemo
    spec:
      containers:
      - name: cbdemo
        image: harbor.tanzuworld.com/cbdemo/spring-http
        ports:
        - containerPort: 8080
