#cloud-config
users:
  - default
  - name: vmware
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    # Password set to Admin!23
    passwd: '$1$salt$SOC33fVbA/ZxeIwD5yw1u1'
    shell: /bin/bash
ssh_pwauth: true

write_files:
  - content: |
      VMSVC Says Hello World
    path: /helloworld

apt:
  preserve_sources_list: true
  sources:
    elasticsearch:
      source: deb https://artifacts.elastic.co/packages/7.x/apt stable main
      keyid: D88E42B4

package_update: true
packages:
  - apt-transport-https
  - elasticsearch
  - kibana

runcmd:
  - "echo 'server.host: 0.0.0.0' >> /etc/kibana/kibana.yml"
  - systemctl daemon-reload
  - systemctl enable elasticsearch.service
  - systemctl restart elasticsearch.service
  - systemctl enable kibana.service
  - systemctl restart kibana.service
