---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cbdemo-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: cbdemo
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""