apiVersion: v1
kind: ConfigMap
metadata:
  name: vsphere.provider.config.vmoperator.vmware.com
  namespace: default
data:
  VcPNID: 10.161.173.218
  VcCredsSecretName: wcp-vmop-sa-vc-auth
  Datacenter: <datacenter-moId>
  ResourcePool: <resourcepool-moId>
  Folder: <folder-moId>
  Datastore: nfs0-1
  ContentSource: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: wcp-vmop-sa-vc-auth
  namespace: default
type: Opaque
data:
  username: QWRtaW5pc3RyYXRvckB2c3BoZXJlLmxvY2Fs
  password: QWRtaW4hMjM=
