kind: Namespace
apiVersion: v1
metadata:
  name: 99999-9000-a05-t3-dev
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: management-ui 
  namespace: 99999-9000-a05-t3-dev 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        namespace: 99999-9000-a05-t3-dev 
    spec:
      containers:
      - name: management-ui
        image: calico/star-collect:v0.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: management-ui 
  namespace: 99999-9000-a05-t3-dev 
spec:
  type: NodePort
  ports:
  - port: 9001 
    targetPort: 9001
    nodePort: 30002
  selector:
    namespace: 99999-9000-a05-t3-dev 
