kind: Namespace
apiVersion: v1
metadata:
  name: 99990-9002-a05-t3-dev
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: client
  namespace: 99990-9002-a05-t3-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        namespace: 99990-9002-a05-t3-dev
    spec:
      containers:
      - name: client 
        image: calico/star-probe:v0.1.0
        imagePullPolicy: Always
        command:
        - probe
        - --http-port=9000
        - --http-probe-seconds=10
        - --urls=http://psaas.99991-9001-a03-t1-prod:443/status,http://web.99994-1001-a05-t2-dev:443/status,http://app.99994-1002-a05-t3-dev:9443/status,http://db.99993-1003-a05-t4-dev:1521/status,http://client.99990-9002-a01-t3-prod:9000/status,http://web.99994-1001-a03-t2-prod:443/status,http://app.99994-1002-a03-t3-prod:9443/status,http://db.99993-1003-a03-t4-prod:1521/status
        ports:
        - containerPort: 9000 
---
apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: 99990-9002-a05-t3-dev
spec:
  ports:
  - port: 9000 
    targetPort: 9000
  selector:
    namespace: 99990-9002-a05-t3-dev
