apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsx-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nsxdemo
  template:
    metadata:
      labels:
        app: nsxdemo
    spec:
      containers:
      - name: nsx-demo
        image: yfauser/nsx-demo
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: nsx-demo-svc
  labels:
    app: nsxdemo
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
      protocol: TCP
      name: tcp
  selector:
    app: nsxdemo
  type: LoadBalancer
