apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: dev-cluster
spec:
  topology:
    controlPlane:
      count: 1
      class: best-effort-xsmall
      storageClass: k8s-storage-policy
    workers:
      count: 1
      class: best-effort-xsmall
      storageClass: k8s-storage-policy
  distribution:
    version: v1.18
