kind: Namespace
apiVersion: v1
metadata:
  name: 99993-1003-a03-t4-prod
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: db 
  namespace: 99993-1003-a03-t4-prod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        namespace: 99993-1003-a03-t4-prod 
    spec:
      containers:
      - name: db 
        image: calico/star-probe:v0.1.0
        imagePullPolicy: Always
        command:
        - probe
        - --http-port=1521
        - --http-probe-seconds=10
        - --urls=http://client.99990-9002-a05-t3-dev:9000/status,http://psaas.99991-9001-a05-t1-dev:443/status,http://web.99994-1001-a05-t2-dev:443/status,http://app.99994-1002-a05-t3-dev:9443/status,http://client.99990-9002-a01-t3-prod:9000/status,http://psaas.99991-9001-a03-t1-prod:443/status,http://web.99994-1001-a03-t2-prod:443/status,http://app.99994-1002-a03-t3-prod:9443/status,,http://db.99993-1003-a05-t4-dev:1521/status
        ports:
        - containerPort: 1521 
---
apiVersion: v1
kind: Service
metadata:
  name: db 
  namespace: 99993-1003-a03-t4-prod
spec:
  ports:
  - port: 1521
    targetPort: 1521 
  selector:
    namespace: 99993-1003-a03-t4-prod
