#! For beta-2 only self-signed certificate issuer is supported.
apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: Trait
metadata:
  name: selfsigned-certificate-issuer
spec:
  description: Configures certificates and certificate issuers to facilitate data encryption and authentication for space services.
  carvelPackages:
  - alias: multicloud-cert-manager.tanzu.vmware.com
    refName: multicloud-cert-manager.tanzu.vmware.com
    versionSelection:
      constraints: 2.0.0-build.1 #For Beta 2, the version of the multicloud-cert-manager.tanzu.vmware.com is 2.0.0-build.1. Ensure to keep the version updated
    values:
      inline:
