apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: harbor.tanzuworld.com/cbdemo/cbdemocd
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: demo
  name: demo
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: demo
  type: LoadBalancer
